[lint]
select = ["E", "F", "I"]
ignore = ["E501"]

[lint.isort]
known-first-party = ["main"]
known-third-party = ["psycopg2", "fastapi", "pydantic", "uvicorn", "prometheus_fastapi_instrumentator", "pytest"]