apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: microdeploy-api
  namespace: microdeploy
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: microdeploy-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
