# -----------------------------------------------------------------------------
# Dev overlay -- builds on base, 1 API replica, lower resource limits
# -----------------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: microdeploy
resources:
  - ../base
  - namespace.yaml
  - sealed-secret.yaml
images:
  - name: ghcr.io/amenmnx/microdeploy-api
    newTag: 5001e3cca962d011e57ed573665042cd873a596b
  - name: ghcr.io/amenmnx/microdeploy-worker
    newTag: 5001e3cca962d011e57ed573665042cd873a596b
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: microdeploy-api
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "300m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "192Mi"
    target:
      kind: Deployment
      name: microdeploy-api
