---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: microdeploy-secret
  namespace: microdeploy
spec:
  encryptedData:
    DB_PASSWORD: AgBBbiz9A1A1pxGOXTyRgcNPNxdc9VEEF9kYTTv2hS3pA9BDbbFn6Ua14cVx+18rAvPH78K2jlhyURsrgPmW+34T41O71p9TcIb5ceKw+zllsRvZTWeIEIGGxODP/jm6/PTCjzhFzIdNo3syxdb/MJJDNnIKtez5x2uj8aQmkDLQWDiw7Tyn5JCBzdt3mWOgoFQn/f+r9xIxtZ6OW5rArWl2wJdS+PvZiKc+p4aRyObhCzdKdeZ3DfveYGhrI6TxaQyQtIyEbA6VCHMPc+xp4LT9AScHrOZGzkNF0f6eD8tk1vKe6eJ7G+X4L9vrEvTZbLOezMG/dmHiS5nDVM9NL88PowDcBfkjxK5d7ZPI3FSOIWuyMqGf1n4FJZMwmFJf1aoCwsmo0qw2Oj+avSlVC/+tFJTruJ4ythRb4ih6Hm6j5efZV6gvgCX7Z4XUBDI2IOhBVaBnILU7kh5A2i7VSZQlQg9i5ItBt9UfQWP1WyTFMSh3EcFLycnbj45V2nD9e5/gaTaEtj7lMzQQYtOrUhnayZ5qAMT1b72TkJUicfNs7u6pESS5xPd16DI43yjgM5DROi3oMv5gKmBqkwEoKSx7jNhYlxpMymxvzBpjKo0QRiuf3e4zAd36b6zHm4jGDJZa8z9KCFtg3/wTY5dKMa9kP6BN1KtzdcbXbr+u+nAtXZYotGiI17Dd6TZq5QTxM+BsjG757Sk3uh1kYA==
  template:
    metadata:
      name: microdeploy-secret
      namespace: microdeploy